### ISSUE TITLE
'NoneType' object has no attribute 'extract_cookies'

### ISSUE THREAD

**Issue by Mazawrath** [yihong0618/BingImageCreator#1]
Hi there,
First of all, thank you for fixing this library, I was worried nobody was going to maintain it after it got archived. If you could help with this it would be greatly appreciated.

So I've tried using this library and I'm running into this error.
Oddly enough, this error does not happen in the original repository this forked off of. I'm using a Docker container and I can swap between yours and the old repository, and that one doesn't have this issue.
```
Traceback (most recent call last):
  File "/usr/src/app/bingGPT.py", line 111, in ask
    return image_generator.get_images(image_request.prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/BingImageCreator.py", line 133, in get_images
    response = self.session.post(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 719, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/usr/local/lib/python3.11/site-packages/requests/cookies.py", line 137, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
```
It seems to me that `Requests` itself is the one at fault? I couldn't find what would cause this from your code.
Looking at git blame I can't find any single line that would cause an error like this.

**Comment by yihong0618** [comment]
@Mazawrath sorry for late reply 
please copy the whole cookie and use quota for the cookie

like '${cookie}'
